#!/usr/bin/env bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
PACKAGE_DIR="$(dirname "$SCRIPT_DIR")"
PACKAGE_NAME="$(basename "$PACKAGE_DIR")"

echo "Package name: $PACKAGE_NAME"
